### PR TITLE
fix: include index.d.ts in npm package

### PR DESCRIPTION
**Pull request by stefanprobst**
this includes `index.d.ts` in the npm package (which i forgot to add in https://github.com/jamiebuilds/tailwindcss-animate/pull/32)

### CODE REVIEW

**Review by websiddu — APPROVED** [review]

**Comment by samik966** [comment]
When are we expecting to merge this request?

**Comment by stefanprobst** [comment]
@jamiebuilds could you take a quick look at this? thanks!

**Comment by AlanMorel** [comment]
Would love to see this merged

**Comment by ng-hai** [comment]
You can bypass the error while waiting this PR to be merged
image

**Comment by AlanMorel** [comment]
I moved on from this already, it's too risky to depend on a package with this little activity/support. Thanks though!

**Pull request merged**
